name: Test Netkit

on:
  push:
    branches:
      - master

jobs:
  test_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        version:
          - stable
    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@v1.0.1
      with:
        nim-version: ${{ matrix.version }}
    - name: Install Packages
      run: nimble install -y
    - name: Test command
      run: nimble test

  test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@v1.0.1
      with:
        nim-version: ${{ matrix.version }}
    - name: Install Packages
      run: nimble install -y
    - name: Test command
      run: nimble test
